// Generated by gencpp from file olei_msgs/oleiScan.msg
// DO NOT EDIT!


#ifndef OLEI_MSGS_MESSAGE_OLEISCAN_H
#define OLEI_MSGS_MESSAGE_OLEISCAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <olei_msgs/oleiPacket.h>

namespace olei_msgs
{
template <class ContainerAllocator>
struct oleiScan_
{
  typedef oleiScan_<ContainerAllocator> Type;

  oleiScan_()
    : header()
    , packets()  {
    }
  oleiScan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , packets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::olei_msgs::oleiPacket_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::olei_msgs::oleiPacket_<ContainerAllocator> >> _packets_type;
  _packets_type packets;





  typedef boost::shared_ptr< ::olei_msgs::oleiScan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::olei_msgs::oleiScan_<ContainerAllocator> const> ConstPtr;

}; // struct oleiScan_

typedef ::olei_msgs::oleiScan_<std::allocator<void> > oleiScan;

typedef boost::shared_ptr< ::olei_msgs::oleiScan > oleiScanPtr;
typedef boost::shared_ptr< ::olei_msgs::oleiScan const> oleiScanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::olei_msgs::oleiScan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::olei_msgs::oleiScan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::olei_msgs::oleiScan_<ContainerAllocator1> & lhs, const ::olei_msgs::oleiScan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.packets == rhs.packets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::olei_msgs::oleiScan_<ContainerAllocator1> & lhs, const ::olei_msgs::oleiScan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace olei_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::olei_msgs::oleiScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::olei_msgs::oleiScan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::olei_msgs::oleiScan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::olei_msgs::oleiScan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::olei_msgs::oleiScan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::olei_msgs::oleiScan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::olei_msgs::oleiScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99104d6cdcf01a9d450db883042f49ea";
  }

  static const char* value(const ::olei_msgs::oleiScan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99104d6cdcf01a9dULL;
  static const uint64_t static_value2 = 0x450db883042f49eaULL;
};

template<class ContainerAllocator>
struct DataType< ::olei_msgs::oleiScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "olei_msgs/oleiScan";
  }

  static const char* value(const ::olei_msgs::oleiScan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::olei_msgs::oleiScan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# olei LIDAR scan packets.\n"
"\n"
"Header           header         # standard ROS message header\n"
"oleiPacket[] packets        # vector of raw packets\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: olei_msgs/oleiPacket\n"
"# Raw olei LIDAR packet.\n"
"\n"
"time stamp              # packet timestamp\n"
"uint8[1240] data        # packet contents\n"
"\n"
;
  }

  static const char* value(const ::olei_msgs::oleiScan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::olei_msgs::oleiScan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.packets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct oleiScan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::olei_msgs::oleiScan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::olei_msgs::oleiScan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "packets[]" << std::endl;
    for (size_t i = 0; i < v.packets.size(); ++i)
    {
      s << indent << "  packets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::olei_msgs::oleiPacket_<ContainerAllocator> >::stream(s, indent + "    ", v.packets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OLEI_MSGS_MESSAGE_OLEISCAN_H
